name: "Install dependencies"
description: "Prepare repository and all dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.0.30

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 21

    - name: Set up Foundry
      uses: foundry-rs/foundry-toolchain@v1

      # TODO(3074): Remove this when 3074 supported natively in Anvil.
    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@master

    - name: Install dependencies
      shell: bash
      run: bun install