name: "Setup Wagmi"
description: "Prepare Wagmi repository and all dependencies"

runs:
  using: "composite"
  steps:
    - name: Clone wagmi repo
      shell: bash
      run: gh repo clone wevm/wagmi

    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: ./wagmi/package.json

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        cache-dependency-path: ./wagmi/pnpm-lock.yaml
        node-version: 22

    - name: Build viem
      shell: bash
      run: pnpm build

    - name: Install dependencies
      shell: bash
      run: pnpm install
      working-directory: ./wagmi

    - shell: bash
      run: pnpm i viem@file:../src -w
      working-directory: ./wagmi

    - name: Build packages
      shell: bash
      run: pnpm build
      working-directory: ./wagmi

    - name: Link packages
      shell: bash
      run: pnpm preconstruct
      working-directory: ./wagmi
