name: "Setup Wagmi"
description: "Prepare Wagmi repository and all dependencies"

runs:
  using: "composite"
  steps:
    - name: Clone wagmi repo
      shell: bash
      run: gh repo clone wevm/wagmi

    - name: Set up pnpm
      uses: pnpm/action-setup@v2
      with:
        package_json_file: ./wagmi/package.json

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        cache-dependency-path: ./wagmi/pnpm-lock.yaml
        node-version: 20

    - name: Build viem
      shell: bash
      run: bun run build

    - name: Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts
      working-directory: ./wagmi

    - shell: bash
      run: pnpm link --dir ../wagmi
      working-directory: ./src

    - name: Link packages
      shell: bash
      run: pnpm preconstruct
      working-directory: ./wagmi
