name: Test chains
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - src/chains/definitions/**

jobs:
  test:
    name: Check chains
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 10

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with: 
          submodules: 'recursive'

      - name: Install dependencies
        uses: wevm/actions/.github/actions/bun@main

      - name: Check chain
        run: bun run test:chains
